version: '3.3'
services:
    mysql:
        ports:
            - '33060:3306'
        container_name: mysql-db
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=fulltimetickets
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pass
        volumes:
            - /var/lib/mysql
        image: mysql
        command: --default-authentication-plugin=mysql_native_password